import type { Recipe } from "@/lib/content";

function slugify(title: string) {
  return title
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function recipe(recipe: Omit<Recipe, "slug"> & { slug?: string }): Recipe {
  return {
    slug: recipe.slug ?? slugify(recipe.title),
    synthesizedByGpt55: recipe.synthesizedByGpt55 ?? !recipe.source,
    ...recipe,
  };
}

const pantry = [
  "Salt, black pepper, and neutral oil",
  "Ginger, garlic, onions, and green chilies as needed",
  "Adjust heat, acid, and sweetness at the end",
];

export const recipes: Recipe[] = [
  recipe({
    title: "Peanut noodles with tofu and vegetables",
    dek: "Saucy peanut noodles with crisp tofu, carrots, greens, herbs, and chili oil.",
    cuisine: "East Asian",
    time: "30 min",
    servings: "3-4",
    image: "/images/recipes/peanut-noodles-with-tofu-and-vegetables.jpg",
    tags: ["noodles", "tofu", "weeknight", "vegetarian"],
    ingredients: [
      "Rice noodles or wheat noodles",
      "Extra-firm tofu, pressed and cubed",
      "Carrots, bell peppers, scallions, and greens",
      "Peanut butter, soy sauce, rice vinegar, sesame oil",
      "Chili garlic sauce or chili crisp",
      "Lime, cilantro, basil, and chopped peanuts",
      ...pantry,
    ],
    steps: [
      "Cook noodles until just tender, rinse briefly, and reserve a little cooking water.",
      "Crisp tofu in oil until golden on several sides.",
      "Whisk peanut butter, soy sauce, vinegar, sesame oil, chili sauce, lime, and water into a glossy sauce.",
      "Stir-fry vegetables until bright and still a little crisp.",
      "Toss noodles, tofu, vegetables, and sauce together, loosening with water as needed.",
      "Finish with herbs, scallions, peanuts, and extra chili oil.",
    ],
  }),
  recipe({
    title: "Chili noodles with tofu and vegetables",
    dek: "A spicier noodle bowl with tofu, vegetables, soy, vinegar, and chili crisp.",
    cuisine: "East Asian",
    time: "25 min",
    servings: "3-4",
    image: "/images/recipes/chili-noodles-with-tofu-and-vegetables.jpg",
    tags: ["noodles", "tofu", "spicy", "weeknight"],
    ingredients: [
      "Noodles",
      "Extra-firm tofu",
      "Carrots, cabbage, peppers, mushrooms, or greens",
      "Soy sauce, black vinegar or rice vinegar, sesame oil",
      "Chili crisp or chili garlic sauce",
      "Scallions and cilantro",
      ...pantry,
    ],
    steps: [
      "Boil noodles and drain.",
      "Sear tofu until crisp, then set aside.",
      "Stir-fry vegetables with garlic and ginger.",
      "Add soy sauce, vinegar, sesame oil, and chili crisp.",
      "Toss in noodles and tofu until coated and glossy.",
      "Top with scallions, herbs, and more chili crisp.",
    ],
  }),
  recipe({
    title: "Dan Dan noodles with Impossible meat",
    dek: "A vegetarian dan dan-style noodle bowl with spicy, savory Impossible meat sauce.",
    cuisine: "Sichuan-inspired",
    time: "35 min",
    servings: "4",
    image: "/images/recipes/dan-dan-noodles-with-impossible-meat.jpg",
    tags: ["noodles", "spicy", "fake meat", "dinner"],
    ingredients: [
      "Noodles",
      "Impossible meat",
      "Sichuan peppercorns",
      "Garlic, ginger, scallions",
      "Soy sauce, black vinegar, sesame paste or tahini",
      "Chili oil or chili crisp",
      "Baby bok choy or greens",
      ...pantry,
    ],
    steps: [
      "Toast and grind Sichuan peppercorns.",
      "Brown Impossible meat with garlic, ginger, soy sauce, chili oil, and a pinch of sugar.",
      "Whisk sesame paste, soy sauce, vinegar, chili oil, and hot noodle water into a sauce.",
      "Cook noodles and blanch greens in the same pot.",
      "Serve noodles with sauce, meat, greens, scallions, and more chili oil.",
    ],
  }),
  recipe({
    title: "Mapo tofu and garlic eggplant",
    dek: "Silken tofu and eggplant in a spicy, numbing sauce with mushrooms or vegetarian mince.",
    cuisine: "Sichuan-inspired",
    time: "40 min",
    servings: "4",
    image: "/images/recipes/mapo-tofu-and-garlic-eggplant.jpg",
    tags: ["tofu", "spicy", "rice", "vegetarian"],
    source: "Adapted from the Spicy Delicious cookbook.",
    ingredients: [
      "Silken or soft tofu, cubed",
      "Eggplant, cut into batons",
      "Shiitake mushrooms or vegetarian mince",
      "Sichuan peppercorns",
      "Ginger, garlic, scallions",
      "Spicy bean sauce, chili garlic sauce, soy sauce",
      "Cornstarch slurry",
      ...pantry,
    ],
    steps: [
      "Fry or roast eggplant until tender and browned.",
      "Bloom Sichuan peppercorns in oil, then add ginger, garlic, mushrooms, and chili sauces.",
      "Add water or broth and simmer into a sauce.",
      "Slide in tofu and eggplant gently so the tofu stays intact.",
      "Thicken with cornstarch slurry and finish with scallions.",
      "Serve with rice.",
    ],
  }),
  recipe({
    title: "Black pepper tofu and rice",
    dek: "A buttery, peppery tofu dish with onions, chilies, dark soy, and scallions.",
    cuisine: "East Asian",
    time: "30 min",
    servings: "4",
    image: "/images/recipes/black-pepper-tofu-and-rice.jpg",
    tags: ["tofu", "rice", "spicy", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Soft tofu",
      "Red onion",
      "Garlic, ginger, red chili, and Thai green chilies",
      "Whole black pepper, coarsely ground",
      "Light soy sauce and dark soy sauce",
      "Sugar and butter or oil",
      "Green onions",
      "Rice, for serving",
    ],
    steps: [
      "Saute garlic, ginger, chilies, and onion in butter or oil.",
      "Add coarsely ground black pepper and let it bloom.",
      "Add sugar, light soy, and dark soy, then simmer into a glossy sauce.",
      "Add tofu and green onions, spooning sauce over the tofu.",
      "Serve hot over rice.",
    ],
  }),
  recipe({
    title: "Peanut tofu and rice",
    dek: "Crispy baked tofu with peanut-lime sauce, herbs, and rice.",
    cuisine: "East Asian",
    time: "35 min",
    servings: "2-3",
    image: "/images/recipes/peanut-tofu-and-rice.jpg",
    tags: ["tofu", "rice", "peanut", "weeknight"],
    source: "Inspired by the Spicy Delicious baked crispy peanut tofu notes.",
    ingredients: [
      "Extra-firm tofu",
      "Cornstarch",
      "Peanut butter, tamari or soy sauce",
      "Chili garlic sauce",
      "Lime juice, maple syrup, sesame oil",
      "Green onions and cilantro",
      "Cooked rice",
      ...pantry,
    ],
    steps: [
      "Press tofu, cube it, toss with oil and cornstarch, and bake or air-fry until crisp.",
      "Whisk peanut butter, soy sauce, chili garlic sauce, lime, maple, sesame oil, and water.",
      "Warm the sauce gently until pourable.",
      "Serve tofu over rice with sauce, scallions, cilantro, and lime.",
    ],
  }),
  recipe({
    title: "Sheet pan miso maple tofu and rice",
    dek: "Hands-off roasted tofu and vegetables glazed with miso, maple, soy, and sesame.",
    cuisine: "Japanese-inspired",
    time: "40 min",
    servings: "4",
    image: "/images/recipes/sheet-pan-miso-maple-tofu-and-rice.jpg",
    tags: ["sheet pan", "tofu", "rice", "weeknight"],
    ingredients: [
      "Extra-firm tofu",
      "Broccoli, sweet potato, mushrooms, carrots, or Brussels sprouts",
      "White miso",
      "Maple syrup",
      "Soy sauce, rice vinegar, sesame oil",
      "Cooked rice",
      "Sesame seeds and scallions",
      ...pantry,
    ],
    steps: [
      "Heat oven to 425 F.",
      "Whisk miso, maple, soy sauce, vinegar, sesame oil, and a splash of water.",
      "Toss tofu and vegetables with glaze on a sheet pan.",
      "Roast until browned, flipping once.",
      "Serve over rice with sesame seeds and scallions.",
    ],
  }),
  recipe({
    title: "Sheet pan shawarma and pita",
    dek: "Shawarma-spiced vegetables and protein with warm pita, herbs, and yogurt sauce.",
    cuisine: "Middle Eastern-inspired",
    time: "40 min",
    servings: "4",
    image: "/images/recipes/sheet-pan-shawarma-and-pita.jpg",
    tags: ["sheet pan", "pita", "weeknight"],
    ingredients: [
      "Cauliflower, chickpeas, onions, peppers, or tofu",
      "Cumin, coriander, paprika, turmeric, cinnamon, cayenne",
      "Pita",
      "Yogurt or tahini sauce",
      "Cucumber, tomato, herbs, lemon",
      ...pantry,
    ],
    steps: [
      "Heat oven to 425 F.",
      "Toss vegetables and protein with oil, shawarma spices, salt, and pepper.",
      "Roast until browned and crisp at the edges.",
      "Warm pita and make a quick yogurt or tahini sauce with lemon and garlic.",
      "Serve everything with herbs and chopped salad.",
    ],
  }),
  recipe({
    title: "Shredded king oyster mushroom tacos",
    dek: "Pulled king oyster mushrooms with smoky adobo-style seasoning and lime.",
    cuisine: "Mexican-inspired",
    time: "35 min",
    servings: "3-4",
    image: "/images/recipes/shredded-king-oyster-mushroom-tacos.jpg",
    tags: ["tacos", "mushrooms", "vegetarian"],
    ingredients: [
      "King oyster mushrooms, shredded with a fork",
      "Corn tortillas",
      "Ancho or chipotle chile powder",
      "Cumin, smoked paprika, oregano",
      "Onion, garlic, lime",
      "Salsa, cilantro, avocado, and pickled onions",
      ...pantry,
    ],
    steps: [
      "Shred mushrooms into strands.",
      "Cook onion and garlic, then add mushrooms and spices.",
      "Sear until mushrooms are browned and slightly crisp.",
      "Finish with lime juice.",
      "Serve in warm tortillas with salsa, cilantro, and pickled onions.",
    ],
  }),
  recipe({
    title: "Mixed mushroom tacos",
    dek: "A fast taco filling with mixed mushrooms, cumin, chile, lime, and cilantro.",
    cuisine: "Mexican-inspired",
    time: "25 min",
    servings: "3-4",
    image: "/images/recipes/mixed-mushroom-tacos.jpg",
    tags: ["tacos", "mushrooms", "weeknight"],
    ingredients: [
      "Mixed mushrooms, sliced",
      "Corn tortillas",
      "Onion and garlic",
      "Cumin, chili powder, smoked paprika",
      "Lime, cilantro, salsa",
      ...pantry,
    ],
    steps: [
      "Cook mushrooms in a wide skillet until they release liquid and brown.",
      "Add onions, garlic, spices, and salt.",
      "Cook until concentrated and savory.",
      "Finish with lime and cilantro.",
      "Serve with tortillas and salsa.",
    ],
  }),
  recipe({
    title: "Tofu tacos",
    dek: "Crumbled tofu taco filling with turmeric, cumin, oregano, chili, and lime.",
    cuisine: "Mexican-inspired",
    time: "25 min",
    servings: "3-4",
    image: "/images/recipes/tofu-tacos.jpg",
    tags: ["tacos", "tofu", "weeknight"],
    source: "Inspired by the cookbook's huevos con papas y chorizo tacos.",
    ingredients: [
      "Extra-firm tofu, crumbled",
      "Corn or flour tortillas",
      "Turmeric, cumin, oregano, paprika, cayenne",
      "Soy chorizo, optional",
      "Potatoes, optional",
      "Cilantro, salsa, lime",
      ...pantry,
    ],
    steps: [
      "Crumble tofu and season with spices, salt, and a splash of water.",
      "Cook potatoes separately if using.",
      "Saute tofu with soy chorizo until browned and flavorful.",
      "Pile into warm tortillas with salsa, cilantro, and lime.",
    ],
  }),
  recipe({
    title: "Mixed vegetable tacos",
    dek: "Weeknight vegetable tacos with peppers, zucchini, mushrooms, beans, and salsa.",
    cuisine: "Mexican-inspired",
    time: "30 min",
    servings: "4",
    image: "/images/recipes/mixed-vegetable-tacos.jpg",
    tags: ["tacos", "vegetables", "weeknight"],
    ingredients: [
      "Peppers, zucchini, mushrooms, onions, or cauliflower",
      "Black beans or pinto beans",
      "Cumin, chili powder, oregano",
      "Tortillas",
      "Salsa, cheese, crema, avocado, cilantro",
      ...pantry,
    ],
    steps: [
      "Saute vegetables over high heat until browned.",
      "Add beans and spices, then cook until hot.",
      "Warm tortillas.",
      "Serve with salsa, avocado, cilantro, and lime.",
    ],
  }),
  recipe({
    title: "Fake meat tacos",
    dek: "Fast taco-night filling with Impossible meat, spices, salsa, and lime.",
    cuisine: "Mexican-inspired",
    time: "20 min",
    servings: "4",
    image: "/images/recipes/fake-meat-tacos.jpg",
    tags: ["tacos", "fake meat", "weeknight"],
    ingredients: [
      "Impossible meat or other plant-based ground",
      "Taco seasoning or cumin, chili powder, paprika, oregano",
      "Onion and garlic",
      "Tortillas",
      "Salsa, lettuce, cheese, cilantro, lime",
      ...pantry,
    ],
    steps: [
      "Brown plant-based meat with onion and garlic.",
      "Add spices and a splash of water or salsa.",
      "Simmer until saucy and seasoned.",
      "Serve with tortillas and toppings.",
    ],
  }),
  recipe({
    title: "Bhindi masala",
    dek: "Okra with onions, tomatoes, chilies, cumin, ginger, garlic, and sabzi masala.",
    cuisine: "Indian",
    time: "25 min",
    servings: "2-3",
    image: "/images/recipes/bhindi-masala.jpg",
    tags: ["indian", "vegetables", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Okra, chopped into 1-inch pieces",
      "Tomatoes, cubed",
      "Red onion, sliced",
      "Green chilies, ginger, garlic",
      "Cumin seeds",
      "Sabzi masala and tawa fry masala",
      ...pantry,
    ],
    steps: [
      "Add oil to a hot pan with cumin, green chilies, ginger, and garlic.",
      "Add onions and cook until softened.",
      "In a separate dry pan, cook okra on medium-high to reduce sliminess.",
      "Add okra to the onion mixture with tomatoes, masala, and salt.",
      "Cook until okra is tender and tomatoes have softened.",
    ],
  }),
  recipe({
    title: "Paneer tikka masala",
    dek: "Paneer, peas, and spinach in a smooth tomato-onion-cashew masala.",
    cuisine: "Indian",
    time: "35 min",
    servings: "4-5",
    image: "/images/recipes/paneer-tikka-masala.jpg",
    tags: ["indian", "paneer", "cookbook"],
    source: "Adapted from the cookbook's mattar paneer tikka masala.",
    ingredients: [
      "Paneer, cubed",
      "Yogurt, for marinating",
      "Tomatoes, red onion, ginger, garlic",
      "Cashews and Thai green chilies",
      "Cumin, chili powder, turmeric, garam masala, sabzi masala",
      "Peas, spinach, cilantro",
      ...pantry,
    ],
    steps: [
      "Marinate paneer in yogurt, salt, and spices for 30 minutes if time allows.",
      "Saute cumin, chilies, ginger, garlic, tomatoes, onion, cashews, and spices.",
      "Blend into a smooth orange sauce.",
      "Return sauce to the pan with water, peas, spinach, and paneer.",
      "Simmer gently, adjust salt, and finish with cilantro.",
    ],
  }),
  recipe({
    title: "Impossible burgers",
    dek: "Simple plant-based burgers with sharp toppings and a good toasted bun.",
    cuisine: "American",
    time: "20 min",
    servings: "4",
    image: "/images/recipes/impossible-burgers.jpg",
    tags: ["burgers", "fake meat", "quick"],
    ingredients: [
      "Impossible patties",
      "Burger buns",
      "Cheese, optional",
      "Lettuce, tomato, onion, pickles",
      "Ketchup, mustard, mayo, or special sauce",
      ...pantry,
    ],
    steps: [
      "Season patties lightly.",
      "Cook in a hot skillet until deeply browned on both sides.",
      "Add cheese if using and cover briefly to melt.",
      "Toast buns.",
      "Assemble with sauces and toppings.",
    ],
  }),
  recipe({
    title: "Rasam and rice",
    dek: "Tomato-tamarind rasam with dal, jaggery, rasam powder, cilantro, and rice.",
    cuisine: "Indian",
    time: "25 min",
    servings: "4-5",
    image: "/images/recipes/rasam-and-rice.jpg",
    tags: ["indian", "soup", "rice", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Toor dal",
      "Tomatoes",
      "Rasam powder",
      "Tamarind",
      "Jaggery",
      "Cilantro",
      "Cooked rice",
      ...pantry,
    ],
    steps: [
      "Cook dal with water and chopped tomatoes until soft.",
      "Add cooked dal to more boiling water to make a thin soup.",
      "Add tamarind, jaggery, salt, and rasam powder.",
      "Simmer until balanced and aromatic.",
      "Finish with cilantro and serve with rice.",
    ],
  }),
  recipe({
    title: "Sambar and rice",
    dek: "Comforting lentil and vegetable sambar with tamarind, sambar powder, and rice.",
    cuisine: "Indian",
    time: "45 min",
    servings: "4-6",
    image: "/images/recipes/sambar-and-rice.jpg",
    tags: ["indian", "lentils", "rice"],
    ingredients: [
      "Toor dal",
      "Onions, tomatoes, spinach, drumstick, carrots, or squash",
      "Tamarind",
      "Sambar powder",
      "Mustard seeds, curry leaves, dried red chilies",
      "Cooked rice",
      ...pantry,
    ],
    steps: [
      "Cook dal until soft and mash lightly.",
      "Simmer vegetables with tamarind, sambar powder, and salt.",
      "Add dal and water to reach a soup-like consistency.",
      "Temper mustard seeds, curry leaves, and chilies in oil, then stir into sambar.",
      "Serve with rice.",
    ],
  }),
  recipe({
    title: "Gobi sabji",
    dek: "Cauliflower cooked with tomatoes, onions, cumin, chilies, and masala.",
    cuisine: "Indian",
    time: "25 min",
    servings: "2-3",
    image: "/images/recipes/gobi-sabji.jpg",
    tags: ["indian", "vegetables", "cookbook"],
    source: "Adapted from the cookbook's gobi masala.",
    ingredients: [
      "Cauliflower florets",
      "Tomatoes",
      "Red onion",
      "Green chilies",
      "Cumin seeds",
      "Sabzi masala and tawa fry masala",
      ...pantry,
    ],
    steps: [
      "Bloom cumin, green chilies, and ginger in oil.",
      "Add cauliflower and cook until it starts to soften.",
      "Add tomatoes, masalas, and salt.",
      "Cook until tender and saucy.",
    ],
  }),
  recipe({
    title: "Dal makhani",
    dek: "Slow, creamy black lentils with tomatoes, butter, spices, and rice or naan.",
    cuisine: "Indian",
    time: "1 hr",
    servings: "5-6",
    image: "/images/recipes/dal-makhani.jpg",
    tags: ["indian", "lentils", "comfort"],
    ingredients: [
      "Whole urad dal or black lentils",
      "Kidney beans, optional",
      "Tomatoes or tomato puree",
      "Ginger, garlic, onion",
      "Cumin, garam masala, chili powder",
      "Butter or cream",
      ...pantry,
    ],
    steps: [
      "Soak lentils if needed, then cook until very soft.",
      "Make a masala with onion, ginger, garlic, tomatoes, and spices.",
      "Add lentils and simmer, stirring often.",
      "Finish with butter or cream and adjust salt.",
      "Serve with rice or naan.",
    ],
  }),
  recipe({
    title: "Vegetable rice",
    dek: "A flexible spiced rice with mixed vegetables, herbs, and optional paneer or tofu.",
    cuisine: "Indian",
    time: "30 min",
    servings: "4",
    image: "/images/recipes/vegetable-rice.jpg",
    tags: ["rice", "vegetables", "weeknight"],
    ingredients: [
      "Basmati rice",
      "Mixed vegetables",
      "Onion, ginger, garlic, green chilies",
      "Cumin, turmeric, garam masala, bay leaf",
      "Cilantro and lime",
      ...pantry,
    ],
    steps: [
      "Rinse rice until water runs mostly clear.",
      "Saute onion, ginger, garlic, chilies, and spices.",
      "Add vegetables and rice, then stir to coat.",
      "Add water, cover, and cook until rice is tender.",
      "Rest, fluff, and finish with cilantro and lime.",
    ],
  }),
  recipe({
    title: "Thai curry",
    dek: "Green or red curry with coconut milk, vegetables, tofu, basil, and chilies.",
    cuisine: "Thai",
    time: "35 min",
    servings: "4",
    image: "/images/recipes/thai-curry.jpg",
    tags: ["thai", "curry", "tofu", "cookbook"],
    source: "Adapted from Aoy's Thai green curry and the Thai red curry notes.",
    ingredients: [
      "Thai curry paste",
      "Coconut milk",
      "Eggplant, mushrooms, carrots, tomatoes, or other vegetables",
      "Firm tofu",
      "Soy sauce",
      "Basil and green onions",
      "Thai chilies, garlic, ginger, or galangal",
      ...pantry,
    ],
    steps: [
      "Toast curry paste with garlic, chilies, ginger, or galangal until aromatic.",
      "Add coconut milk and soy sauce.",
      "Add vegetables and simmer until tender.",
      "Add tofu, basil, and green onions.",
      "Adjust salt, sweetness, and heat.",
    ],
  }),
  recipe({
    title: "Tofu pad kra pow",
    dek: "Thai basil tofu with chilies, garlic, soy sauce, and rice.",
    cuisine: "Thai",
    time: "25 min",
    servings: "3-4",
    image: "/images/recipes/tofu-pad-kra-pow.jpg",
    tags: ["thai", "tofu", "rice", "spicy"],
    ingredients: [
      "Firm tofu, crumbled or cubed",
      "Thai basil",
      "Garlic and Thai chilies",
      "Soy sauce, vegetarian oyster sauce, dark soy",
      "Sugar and lime",
      "Cooked jasmine rice",
      ...pantry,
    ],
    steps: [
      "Pound garlic and chilies into a rough paste.",
      "Cook tofu in a hot pan until browned.",
      "Add garlic-chili paste and stir-fry briefly.",
      "Add sauces and sugar, then toss until glossy.",
      "Fold in Thai basil and serve with rice.",
    ],
  }),
  recipe({
    title: "Jambalaya",
    dek: "A vegetarian jambalaya-style rice pot with peppers, tomatoes, spices, and plant sausage.",
    cuisine: "Cajun-inspired",
    time: "45 min",
    servings: "5-6",
    image: "/images/recipes/jambalaya.jpg",
    tags: ["rice", "one pot", "fake meat"],
    ingredients: [
      "Rice",
      "Onion, celery, bell pepper",
      "Garlic, tomatoes, vegetable broth",
      "Cajun seasoning, paprika, thyme, bay leaf",
      "Plant-based sausage or mushrooms",
      "Scallions and parsley",
      ...pantry,
    ],
    steps: [
      "Brown plant sausage or mushrooms and set aside.",
      "Saute onion, celery, pepper, and garlic.",
      "Add rice, tomatoes, broth, spices, and bay leaf.",
      "Simmer covered until rice is tender.",
      "Fold sausage back in and finish with herbs.",
    ],
  }),
  recipe({
    title: "Peanut stew",
    dek: "West African-inspired peanut stew with sweet potatoes, cauliflower, greens, and tomatoes.",
    cuisine: "West African-inspired",
    time: "40 min",
    servings: "5",
    image: "/images/recipes/peanut-stew.jpg",
    tags: ["stew", "peanut", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Peanut oil",
      "Peanut butter",
      "Cauliflower and sweet potatoes",
      "Canned tomatoes",
      "Vegetable broth",
      "Spinach, kale, or collards",
      "Cumin, cayenne, black pepper, lime",
      ...pantry,
    ],
    steps: [
      "Saute onion, garlic, ginger, and green chilies in peanut oil.",
      "Add cauliflower, sweet potatoes, cumin, black pepper, paprika, and cayenne.",
      "Add canned tomatoes and peanut butter, stirring until peanut butter dissolves.",
      "Add broth and simmer until vegetables are tender.",
      "Add greens, simmer briefly, and finish with lime.",
    ],
  }),
  recipe({
    title: "Poblano soup",
    dek: "Roasted poblano soup with onion, garlic, broth, cilantro, and melting cheese.",
    cuisine: "Mexican",
    time: "45 min",
    servings: "4-6",
    image: "/images/recipes/poblano-soup.jpg",
    tags: ["soup", "mexican", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Poblano peppers",
      "Butter or oil",
      "Onion and garlic",
      "Vegetable broth",
      "Thai green chilies, optional",
      "Cilantro, cumin, salt",
      "Oaxacan, asadero, Chihuahua, or Monterey Jack cheese",
      "Queso fresco or tortilla chips, for topping",
    ],
    steps: [
      "Roast poblanos at 450 F until blistered, then peel and seed.",
      "Saute onion, garlic, and chilies in butter or oil.",
      "Add broth and roasted peppers, then simmer.",
      "Add melting cheese and blend until smooth.",
      "Simmer briefly and top with chips and queso fresco.",
    ],
  }),
  recipe({
    title: "Crispy tacos",
    dek: "Pan-crisped tacos with beans, tofu, fake meat, or vegetables and bright toppings.",
    cuisine: "Mexican-inspired",
    time: "30 min",
    servings: "4",
    image: "/images/recipes/crispy-tacos.jpg",
    tags: ["tacos", "crispy", "weeknight"],
    ingredients: [
      "Corn tortillas",
      "Refried beans, tofu, mushrooms, or plant-based meat",
      "Cheese, optional",
      "Lettuce, salsa, crema, cilantro, lime",
      ...pantry,
    ],
    steps: [
      "Prepare a flavorful filling.",
      "Warm tortillas so they fold without cracking.",
      "Fill tortillas lightly and fold.",
      "Pan-fry in a thin layer of oil until crisp on both sides.",
      "Serve with salsa, lettuce, crema, cilantro, and lime.",
    ],
  }),
  recipe({
    title: "Frozen chicken sandwich",
    dek: "A dressed-up freezer sandwich with slaw, pickles, sauce, and a toasted bun.",
    cuisine: "Shortcut",
    time: "15 min",
    servings: "1-2",
    image: "/images/recipes/frozen-chicken-sandwich.jpg",
    tags: ["shortcut", "sandwich", "quick"],
    ingredients: [
      "Frozen vegetarian or chicken-style patty",
      "Buns",
      "Pickles",
      "Shredded cabbage or lettuce",
      "Mayo, hot sauce, mustard, or special sauce",
      ...pantry,
    ],
    steps: [
      "Cook frozen patty until very crisp.",
      "Toast bun.",
      "Mix a quick sauce with mayo, hot sauce, and mustard.",
      "Assemble with pickles, slaw or lettuce, and sauce.",
    ],
  }),
  recipe({
    title: "Frozen baos",
    dek: "Freezer baos turned into an easy meal with chili crisp, cucumbers, herbs, and greens.",
    cuisine: "Shortcut",
    time: "15 min",
    servings: "2",
    image: "/images/recipes/frozen-baos.jpg",
    tags: ["shortcut", "quick"],
    ingredients: [
      "Frozen baos",
      "Cucumber or quick pickles",
      "Chili crisp",
      "Scallions and cilantro",
      "Steamed or sauteed greens",
    ],
    steps: [
      "Steam or microwave baos according to package directions.",
      "Slice cucumbers and herbs.",
      "Serve baos with chili crisp, cucumbers, herbs, and greens.",
    ],
  }),
  recipe({
    title: "Veggie marinara pasta",
    dek: "A vegetable-heavy marinara pasta with mushrooms, zucchini, spinach, and herbs.",
    cuisine: "Italian-inspired",
    time: "30 min",
    servings: "4",
    image: "/images/recipes/veggie-marinara-pasta.jpg",
    tags: ["pasta", "vegetables", "weeknight"],
    ingredients: [
      "Pasta",
      "Marinara sauce",
      "Mushrooms, zucchini, spinach, onions, garlic",
      "Basil, oregano, red pepper flakes",
      "Parmesan or mozzarella, optional",
      ...pantry,
    ],
    steps: [
      "Cook pasta until al dente.",
      "Saute vegetables with garlic and red pepper flakes.",
      "Add marinara and simmer.",
      "Toss pasta with sauce and pasta water.",
      "Finish with herbs and cheese if using.",
    ],
  }),
  recipe({
    title: "Green goddess pasta",
    dek: "Herby green pasta sauce with basil, spinach, lemon, garlic, and creamy richness.",
    cuisine: "California-ish",
    time: "25 min",
    servings: "4",
    image: "/images/recipes/green-goddess-pasta.jpg",
    tags: ["pasta", "herby", "quick"],
    ingredients: [
      "Pasta",
      "Basil, cilantro, parsley, or spinach",
      "Garlic and lemon",
      "Greek yogurt, cashews, avocado, or olive oil",
      "Parmesan or nutritional yeast, optional",
      ...pantry,
    ],
    steps: [
      "Cook pasta and reserve pasta water.",
      "Blend herbs, greens, garlic, lemon, creamy ingredient, salt, and olive oil.",
      "Toss sauce with hot pasta, loosening with pasta water.",
      "Adjust lemon and salt.",
    ],
  }),
  recipe({
    title: "Charro beans with Mexican rice and quesadilla",
    dek: "A full plate of brothy beans, tomato rice, and a crisp cheese quesadilla.",
    cuisine: "Mexican-inspired",
    time: "50 min",
    servings: "4-6",
    image: "/images/recipes/charro-beans-with-mexican-rice-and-quesadilla.jpg",
    tags: ["beans", "rice", "mexican"],
    source: "Mexican rice adapted from the Spicy Delicious cookbook.",
    ingredients: [
      "Pinto beans, cooked or canned",
      "Onion, garlic, tomatoes, jalapeno or serrano",
      "Cumin, oregano, smoked paprika",
      "Rice, tomato paste, vegetable broth, lime",
      "Tortillas and cheese",
      ...pantry,
    ],
    steps: [
      "Simmer beans with onion, garlic, tomatoes, chilies, cumin, oregano, and broth.",
      "Toast rice, then cook with tomato paste, broth, tomatoes, cumin, and salt.",
      "Make quesadillas in a skillet until crisp and melted.",
      "Serve beans with rice, quesadilla, cilantro, and lime.",
    ],
  }),
  recipe({
    title: "Kimchi and bulgogi fried rice",
    dek: "A deeply savory fried rice with kimchi, vegetarian bulgogi, scallions, and sesame.",
    cuisine: "Korean-inspired",
    time: "25 min",
    servings: "3-4",
    image: "/images/recipes/kimchi-and-bulgogi-fried-rice.jpg",
    tags: ["rice", "kimchi", "fake meat", "quick"],
    ingredients: [
      "Day-old rice",
      "Kimchi and kimchi juice",
      "Vegetarian bulgogi or plant-based beef",
      "Garlic, scallions",
      "Soy sauce, gochujang, sesame oil",
      "Sesame seeds and fried egg, optional",
      ...pantry,
    ],
    steps: [
      "Brown vegetarian bulgogi or plant-based beef.",
      "Add garlic, scallions, chopped kimchi, and gochujang.",
      "Add rice and kimchi juice, frying until hot and slightly crisp.",
      "Season with soy sauce and sesame oil.",
      "Top with sesame seeds, scallions, and egg if using.",
    ],
  }),
  recipe({
    title: "Aoy's Som Tum Thai",
    dek: "Green papaya salad with garlic, Thai chilies, lime, long beans, tomatoes, and peanuts.",
    cuisine: "Thai",
    time: "25 min",
    servings: "3-4",
    image: "/images/recipes/aoy-s-som-tum-thai.jpg",
    tags: ["thai", "salad", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Green papaya, shredded",
      "Garlic cloves",
      "Thai chilies",
      "Brown sugar",
      "Lime juice",
      "Soy sauce",
      "Long beans, cherry tomatoes, roasted peanuts",
    ],
    steps: [
      "Shred papaya into long strands.",
      "Pound chilies, garlic, sugar, and peanuts.",
      "Add long beans, papaya, and tomato, then softly pound or mix.",
      "Season with soy sauce and lime juice.",
    ],
  }),
  recipe({
    title: "Vegan pozole rojo",
    dek: "Hominy, mushrooms, calabacitas, and chile broth with crunchy toppings.",
    cuisine: "Mexican",
    time: "1.5 hr",
    servings: "6-8",
    image: "/images/recipes/gobi-manchurian.jpg",
    tags: ["mexican", "soup", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Hominy, drained and rinsed",
      "Vegetable broth",
      "White or crimini mushrooms",
      "Onion, garlic, bay leaves",
      "Calabacitas",
      "Guajillo, ancho, and chiles de arbol",
      "Oregano, cumin, black pepper",
      "Cabbage, cilantro, lime, radishes, oregano, avocado",
    ],
    steps: [
      "Simmer hominy with vegetable broth, onion, garlic, bay leaves, and spices.",
      "Toast or soften dried chilies, then blend into a red sauce.",
      "Saute mushrooms and calabacitas separately.",
      "Add chile sauce and vegetables to the pot and simmer until rich.",
      "Serve with crunchy toppings, lime, and avocado.",
    ],
  }),
  recipe({
    title: "Onion and jalapeno pakora",
    dek: "Crisp fritters with onions, jalapenos, spinach, besan, and pakora masala.",
    cuisine: "Indian",
    time: "20 min",
    servings: "3-4",
    image: "/images/recipes/vegan-pozole-rojo.jpg",
    tags: ["snack", "indian", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Red onions, thinly sliced",
      "Jalapenos, thinly sliced",
      "Spinach",
      "Pakora masala",
      "Besan",
      "Oil for frying",
      "Salt and water",
    ],
    steps: [
      "Thinly slice onions, jalapenos, and spinach.",
      "Add besan, pakora masala, and salt.",
      "Add water slowly until the vegetables are coated in batter.",
      "Scoop small clumps into hot oil and fry until golden.",
      "Drain on paper towels and serve hot.",
    ],
  }),
  recipe({
    title: "Gobi Manchurian",
    dek: "Fried cauliflower tossed in a ginger-garlic chili sauce with soy and cilantro.",
    cuisine: "Indo-Chinese",
    time: "30 min",
    servings: "3-4",
    image: "/images/recipes/jollof-rice.jpg",
    tags: ["snack", "cauliflower", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Cauliflower florets",
      "Cornstarch, flour, chili powder, water",
      "Ginger, garlic, green chilies",
      "Chili garlic sauce, soy sauce, vinegar, brown sugar",
      "Cilantro",
      ...pantry,
    ],
    steps: [
      "Mix cornstarch, flour, water, and chili powder into a smooth batter.",
      "Blanch cauliflower briefly, then dry well.",
      "Dip cauliflower in batter and fry until crisp.",
      "Saute ginger, garlic, chilies, and sauce ingredients.",
      "Toss fried cauliflower in sauce and garnish with cilantro.",
    ],
  }),
  recipe({
    title: "Palak paneer",
    dek: "Paneer in a green spinach sauce with tomatoes, onion, chilies, cashews, and spices.",
    cuisine: "Indian",
    time: "35 min",
    servings: "4-5",
    image: "/images/recipes/palak-paneer.jpg",
    tags: ["indian", "paneer", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Paneer",
      "Spinach",
      "Tomatoes, red onion, ginger, garlic",
      "Cashews and Thai green chilies",
      "Cumin, chili powder, turmeric, garam masala, sabzi masala",
      ...pantry,
    ],
    steps: [
      "Soften paneer in hot water.",
      "Blanch spinach briefly and cool in ice water.",
      "Saute cumin, chilies, ginger, garlic, tomatoes, onions, cashews, and spices.",
      "Blend with spinach into a green sauce.",
      "Simmer sauce with paneer and adjust salt.",
    ],
  }),
  recipe({
    title: "Baingan bhartha",
    dek: "Roasted eggplant mashed into a tomato-onion masala with ginger, garlic, and chilies.",
    cuisine: "Indian",
    time: "35 min",
    servings: "4-5",
    image: "/images/recipes/baingan-bhartha.jpg",
    tags: ["indian", "eggplant", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Large eggplants",
      "Tomatoes and red onion",
      "Ginger, garlic, green chilies",
      "Cumin, chili powder, turmeric, garam masala, sabzi masala",
      "Cilantro",
      ...pantry,
    ],
    steps: [
      "Broil or roast eggplants until collapsed and smoky.",
      "Saute cumin, chilies, ginger, garlic, tomatoes, onions, and spices.",
      "Mash roasted eggplant and add to the masala.",
      "Cook until cohesive and deeply flavored.",
      "Finish with cilantro.",
    ],
  }),
  recipe({
    title: "Dal tadka",
    dek: "Toor dal finished with a tomato-onion tadka, chilies, cumin, turmeric, and chili powder.",
    cuisine: "Indian",
    time: "30 min",
    servings: "3-4",
    image: "/images/recipes/dal-tadka.jpg",
    tags: ["indian", "lentils", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Toor dal",
      "Tomatoes",
      "Red onion",
      "Cumin seeds",
      "Green chilies",
      "Red chili powder and turmeric",
      ...pantry,
    ],
    steps: [
      "Cook dal until soft.",
      "Saute cumin, chilies, onion, tomatoes, turmeric, and chili powder.",
      "Add cooked dal to the tadka.",
      "Simmer and adjust salt and water until the texture is right.",
    ],
  }),
  recipe({
    title: "Jollof rice",
    dek: "Tomato-pepper rice with thyme, curry powder, bay leaves, and smoky browned bits.",
    cuisine: "West African",
    time: "1 hr",
    servings: "4",
    image: "/images/recipes/onion-and-jalapeno-pakora.jpg",
    tags: ["rice", "west african", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Tomatoes",
      "Scotch bonnet or habanero",
      "Onion and bell peppers",
      "Curry powder, ground chile, garlic powder, onion powder",
      "Bay leaves, ginger, thyme",
      "Medium grain rice",
      ...pantry,
    ],
    steps: [
      "Blend tomatoes, hot pepper, and onion.",
      "Cook blended vegetables with spices and bay leaves until concentrated.",
      "Stir in rice and reduce heat.",
      "Cover and cook until rice is tender, adding water if needed.",
      "Let the bottom char slightly for smoky flavor.",
    ],
  }),
  recipe({
    title: "Bagels",
    dek: "Chewy homemade bagels with everything seasoning.",
    cuisine: "Baked goods",
    time: "1.5 hr",
    servings: "8",
    image: "/images/recipes/bagels.jpg",
    tags: ["baking", "bread", "cookbook"],
    source: "From the Spicy Delicious cookbook.",
    ingredients: [
      "Flour",
      "Sugar",
      "Yeast",
      "Warm water",
      "Salt",
      "Everything bagel seasoning",
      "Baking soda, for boiling",
    ],
    steps: [
      "Bloom yeast and sugar in warm water until foamy.",
      "Mix with flour and salt to form a dough.",
      "Knead 5-10 minutes and let rise until expanded.",
      "Divide into 8 balls, rest, then shape into bagels.",
      "Boil briefly with baking soda, top with seasoning, and bake at 425 F until browned.",
    ],
  }),
];
