import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Clock3, Sparkles, UsersRound } from "lucide-react";
import { PasscodeGate } from "@/components/PasscodeGate";
import { getRecipe, recipes } from "@/lib/content";
import { isUnlocked } from "@/lib/auth";

export const metadata = {
  title: "Recipe",
  robots: { index: false, follow: false },
};

export function generateStaticParams() {
  return recipes.map((recipe) => ({ slug: recipe.slug }));
}

export default async function RecipePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;

  if (!(await isUnlocked())) {
    return (
      <PasscodeGate
        title="Recipe notebook"
        description="Enter passcode"
        redirectTo={`/recipes/${slug}`}
      />
    );
  }

  const recipe = getRecipe(slug);
  if (!recipe) notFound();

  return (
    <main className="noise px-4 py-6 sm:px-6 lg:px-8">
      <article className="mx-auto max-w-5xl overflow-hidden rounded-lg border border-ink/12 bg-paper shadow-soft">
        <header className="flex items-center justify-between border-b border-ink/12 px-5 py-5 md:px-7">
          <Link href="/recipes" className="inline-flex items-center gap-2 text-sm text-ink/72 hover:text-ink">
            <ArrowLeft size={18} aria-hidden />
            Recipes
          </Link>
          <p className="text-xs uppercase tracking-[0.16em] text-moss">{recipe.cuisine}</p>
        </header>

        <div className="grid gap-0 lg:grid-cols-[0.95fr_1.05fr]">
          <div className="relative min-h-[320px] border-b border-ink/12 lg:border-b-0 lg:border-r">
            <Image
              src={recipe.image}
              alt=""
              fill
              sizes="(min-width: 1024px) 48vw, 100vw"
              priority
              className="object-cover"
            />
          </div>

          <div className="px-5 py-7 md:px-7 lg:py-10">
            <div className="flex flex-wrap gap-2">
              {recipe.tags.map((tag) => (
                <span key={tag} className="rounded-md border border-ink/14 px-2.5 py-1 text-xs text-ink/64">
                  {tag}
                </span>
              ))}
            </div>
            <h1 className="mt-5 font-serif text-5xl leading-tight text-ink">{recipe.title}</h1>
            <p className="mt-4 text-lg leading-8 text-ink/72">{recipe.dek}</p>
            <p className="mt-5 flex flex-wrap items-center gap-4 text-sm text-ink/62">
              <span className="inline-flex items-center gap-1.5">
                <Clock3 size={16} aria-hidden />
                {recipe.time}
              </span>
              <span className="inline-flex items-center gap-1.5">
                <UsersRound size={16} aria-hidden />
                {recipe.servings} servings
              </span>
            </p>

            {recipe.synthesizedByGpt55 ? (
              <div className="mt-6 rounded-lg border border-moss/20 bg-moss/8 px-4 py-3 text-sm leading-6 text-ink/72">
                <p className="inline-flex items-center gap-2 font-medium text-moss">
                  <Sparkles size={16} aria-hidden />
                  Generated by GPT-5.5
                </p>
                <p className="mt-1">
                  Draft recipe synthesized for the notebook. Treat measurements as a strong starting
                  point and revise after cooking.
                </p>
              </div>
            ) : null}

            {recipe.source ? (
              <p className="mt-4 text-sm leading-6 text-ink/58">{recipe.source}</p>
            ) : null}
          </div>
        </div>

        <div className="grid gap-0 border-t border-ink/12 lg:grid-cols-[0.85fr_1.15fr]">
          <section className="border-b border-ink/12 px-5 py-7 md:px-7 lg:border-b-0 lg:border-r">
            <h2 className="font-serif text-3xl text-ink">Ingredients</h2>
            <ul className="mt-5 space-y-2 text-sm leading-6 text-ink/76">
              {recipe.ingredients.map((ingredient) => (
                <li key={ingredient} className="flex gap-2">
                  <span className="mt-2.5 h-1 w-1 flex-none rounded-full bg-moss" aria-hidden />
                  <span>{ingredient}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="px-5 py-7 md:px-7">
            <h2 className="font-serif text-3xl text-ink">Steps</h2>
            <ol className="mt-5 space-y-4">
              {recipe.steps.map((step, index) => (
                <li key={step} className="grid grid-cols-[32px_1fr] gap-3 text-sm leading-6 text-ink/76">
                  <span className="font-serif text-xl text-moss">{index + 1}</span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </section>
        </div>
      </article>
    </main>
  );
}
